name: ecomm_test_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  badges: ^1.2.0
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/c1.jpg
    - images/c2.jpg
    - images/c3.jpg
    - images/c4.jpg
    - images/back.png
    - images/passs.jpg
    - images/carte/dress.png
    - images/carte/formal.png
    - images/carte/jewery.png
    - images/carte/shirt.png
    - images/carte/shoe.png
    - images/carte/trouser.png
    - images/products/gown (1).jpg
    - images/products/gown (2).jpg
    - images/products/shoe (1).jpg
    - images/products/shoe (2).jpg
    - images/products/shoe (3).jpg
    - images/products/shoe (4).jpg
    - images/products/shoe (5).jpg
    - images/products/shoe (6).jpg
    - images/products/shoe (7).jpg
    - images/products/shoe (8).jpg
    - images/products/shoe (9).jpg
    - images/products/shoe (10).jpg
    - images/products/shoe (11).jpg
    - images/products/shoe (12).jpg
    - images/products/shoe (13).jpg
    - images/products/shoe (14).jpg
    - images/products/shoe (15).jpg
    - images/products/shoe (16).jpg
    - images/products/shoe (17).jpg
    - images/products/shoe (18).jpg
    - images/products/shoe (19).jpg
    - images/products/shoe (20).jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
